### ISSUE TITLE
General TODO-List

### ISSUE THREAD

**Issue by jfhn** [manuEbg/thm-ptas#1]
## Implementierung des Algorithmus

1. [x] Datenstruktur für planare Graphen (Embedding)
    - [Double connected edge list](https://en.wikipedia.org/wiki/Doubly_connected_edge_list)
    - [x] Reduction trait
2. [x] Planare Graphen generieren
    - [x] visualisieren
3. [x] Graph in Donuts unterteilen
    - [x] visualisieren
    - [x] make each ring maximal planar
    - [x] Fake-Root
5. [x] Für jeden Donut eine Nice Baumzerlegung erstellen
    - [x] Approximation, Heuristik oder Library für perfekte Zerlegung
    - [x] visualisieren
6. [x] Für jede Baumzerlegung muss das _Maximum Indepentend Set_ gefunden werden
8. [x] Lösungen der Independent Sets müssen miteinander kombiniert werden

## Testen des Algorithmus

- [x] Vergleich mit optimaler Lösung, Heuristiken oder anderen Approximationen
- [x] Laufzeittests durchführen

## Referenzen

- [Genrieren Planarer Graphen](https://stamm-wilbrandt.de/en/IAI-TR-93-10.ps.pdf) 
- [Embeddings](https://page.math.tu-berlin.de/~felsner/Lehre/GraGeo12/krakau.pdf)
- [Doubly Connected Edge List 1](https://www.ics.uci.edu/~goodrich/teach/geom/notes/PointLocation.pdf)
- [Planar Embedding NetworkX](https://networkx.org/documentation/stable/reference/algorithms/generated/generated/networkx.algorithms.planarity.PlanarEmbedding.adj.html#planarembedding-adj)
